<?xml version="1.0" encoding="UTF-8" ?>
<testsuites disabled="0" errors="0" failures="2" tests="4" time="20.595">
 <testsuite name="Protein Search testing" timestamp="2019-05-02T03:27:21" hostname="localhost" time="20.595" errors="0" tests="4" skipped="0" disabled="0" failures="2">
  <testcase classname="Protein Search testing" name="should go to Protein Search page" time="4.817" />
  <testcase classname="Protein Search testing" name="should go to Protein list page" time="11.248" />
  <testcase classname="Protein Search testing" name="number of results found" time="2.044">
   <failure type="toContain" message="Expected &apos;&quot;3 Proteins were found&quot;&apos; to contain &apos;31&apos;."><![CDATA[Error: Failed expectation
    at UserContext.<anonymous> (/Applications/MAMP/htdocs/glygen-frontend/protractor_test/spec.js:45:28)
    at /usr/local/lib/node_modules/protractor/node_modules/jasminewd2/index.js:112:25
    at new ManagedPromise (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1077:7)
    at ControlFlow.promise (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2505:12)
    at schedulerExecute (/usr/local/lib/node_modules/protractor/node_modules/jasminewd2/index.js:95:18)
    at TaskQueue.execute_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:3084:14)
    at TaskQueue.executeNext_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:3067:27)
    at asyncRun (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2974:25)
    at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:668:7]]>
   </failure>
  </testcase>
  <testcase classname="Protein Search testing" name="number of records displayed per page should match the selection" time="2.483">
   <failure type="toEqual" message="Expected 3 to equal 31."><![CDATA[Error: Failed expectation
    at /Applications/MAMP/htdocs/glygen-frontend/protractor_test/spec.js:55:22
    at ManagedPromise.invokeCallback_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1376:14)
    at TaskQueue.execute_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:3084:14)
    at TaskQueue.executeNext_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:3067:27)
    at asyncRun (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2927:27)
    at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:668:7
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)]]>
   </failure>
  </testcase>
 </testsuite>
</testsuites>